version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance_trading_analytics_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      - db

  # db:
  #   image: postgres:15
  #   container_name: binance_trading_analytics_db
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   ports:
  #     - "${DB_PORT}:${DB_PORT}"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

volumes:
  db_data: