version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binance_trading_analytics_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs/app:/app/logs/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - CUSTOM_LOG_DIR=/app/logs/app
    env_file:
      - .env

volumes:
  db_data: