FROM apache/airflow:2.5.1-python3.9

USER root

# Cài curl và các package phụ trợ
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl ca-certificates build-essential gcc libpq-dev libffi-dev libssl-dev \
    gosu \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Cài đặt uv và di chuyển binary ra thư mục toàn cục
RUN sh /uv-installer.sh && \
    cp /root/.local/bin/uv /usr/local/bin/uv && \
    rm /uv-installer.sh

# Copy các file cần thiết vào container
COPY requirements.txt /opt/airflow/requirements.txt
COPY src /opt/airflow/src

# Copy pyproject.toml vào container
COPY pyproject.toml /opt/airflow/pyproject.toml
COPY uv.lock /opt/airflow/uv.lock

# Chuyển vào đúng working directory để uv hoạt động
WORKDIR /opt/airflow

# Chuyển sang người dùng airflow
USER airflow

# Chạy lệnh đồng bộ dependencies
RUN uv sync --frozen
